#!/usr/bin/env bash

# Prints the fzf-selected project path to stdout, or exits 1 if cancelled.
dirs=(
    "$HOME/projects"
    "$HOME/michigan/eecs482/"
)
append="$HOME/.dotfiles $HOME/.local/share/nvim/lazy/ $HOME/michigan/eecs376/hw"

MAGENTA=$'\033[1;35m'
BLUE=$'\033[1;34m'
RESET=$'\033[0m'

append=$(echo "$append" | tr ' ' '\n')

# shellcheck disable=SC2016
selected=$( \
    {
        find "${dirs[@]}" -mindepth 1 -maxdepth 1 -type d
        printf '%s' "$append"
    } \
    | sed "s|^$HOME|${MAGENTA}~${RESET}|" \
    | sed -E "s|(.*/)([^/]+)$|\1${BLUE}\2${RESET}|" \
    | fzf --ansi \
        --reverse \
        --height=100% \
        --preview-window=right:75% \
        --preview 'bash -c '\'' \
            proj=$(basename "{}")
            tmux has-session -t "$proj" 2>/dev/null
            if [ $? == 0 ]; then
                tmux capture-pane -pet "$proj:0"
            else
                printf "\n  \033[1;35m$\033[0;37m tmux new -s \033[1;34m$proj"
            fi
        '\'''
)
[ -z "$selected" ] && exit 1
printf '%s\n' "${selected/#\~/$HOME}"
