#!/opt/homebrew/bin/lua

local ok, projfile = pcall(require, "projfile")
if not ok then
    print("No projfile found in current project.")
    os.exit(1)
end

local COLORS = {}
COLORS.SYMBOL_COLOR = "\x1b[1;44m\x1b[38;5;16m"
COLORS.RESET = "\x1b[0m"
COLORS.BOLD = "\x1b[22;97m"
COLORS.PURPLE = "\x1b[1;35m"

local function preview(cmd)
    local task_str = ""
    if type(cmd) ~= "table" then
        return cmd
    end

    for k, subcmd in pairs(cmd) do
        if k ~= "tag" and k ~= "qf" then
            local suffix = ""
            if #cmd > 1 then
                suffix = " -> ..."
            end
            return preview(subcmd) .. suffix
        end
    end
    return task_str
end

local version = projfile.version
if arg[1] == nil then
    for k, v in pairs(projfile.tasks) do
        if version == "0.1.0" then
            print(k, v)
        else
            print(k, "| " .. preview(v))
        end
    end
    return
end

local silent = arg[2] == "--silent"

local task = arg[1]
if version == "0.1.0" then
    print("Consider reformatting to version 0.1.1")
    os.execute(projfile.tasks[task])
    return
end

if not projfile.tasks[task] then
    print("Task `" .. task .. "` not found in projfile.")
    os.exit(1)
end

local uv = require("luv")
local is_tty = uv.guess_handle(1) == "tty"

local SYMBOL = "[*] "
local MESSAGE = "Executing task `" .. task .. "`"
local PREFIX = "$ "

local wrap_tag = function(tag) return tag end
if is_tty then
    SYMBOL = COLORS.SYMBOL_COLOR .. " * " .. COLORS.RESET .. " "
    MESSAGE = COLORS.BOLD .. "Executing task" .. " `" .. task .. "`" .. COLORS.RESET
    PREFIX = COLORS.PURPLE .. "$ " .. COLORS.RESET
    wrap_tag = function(tag)
        return COLORS.BOLD .. tag .. COLORS.RESET
    end
end

if not silent then
    print(SYMBOL .. MESSAGE)
end
local function run_commands(cmd)
    if type(cmd) == "table" then
        if cmd.tag and not silent then
            print(wrap_tag(cmd.tag))
        end

        for k, subcmd in pairs(cmd) do
            if k ~= "tag" and k ~= "qf" then
                run_commands(subcmd)
            end
        end
    else
        if not silent then
            print(PREFIX .. cmd)
        end
        -- TODO: Track exit codes and exit based on result
        -- https://www.stackoverflow.com/questions/63332954
        os.execute(cmd)
    end
end

for _, command in ipairs(projfile.tasks[task]) do
    run_commands(command)
end
