#!/opt/homebrew/bin/lua

local ok, projfile = pcall(require, "projfile")
if not ok then
    print("No projfile found in current project.")
    return
end

local COLORS = {}
COLORS.SYMBOL_COLOR = "\x1b[1;44m\x1b[38;5;16m"
COLORS.RESET = "\x1b[0m"
COLORS.BOLD = "\x1b[22;97m"
COLORS.PURPLE = "\x1b[1;35m"

local version = projfile.version
if arg[1] == nil then
    for k, v in pairs(projfile.tasks) do
        if version == "0.1.0" then
            print(k, v)
        else
            local task_str = ""
            for _, str in ipairs(v) do
                task_str = task_str .. " -> " .. str
            end
            print(k, "| " .. task_str:sub(4, -1))
        end
    end
    return
end

local task = arg[1]
if version == "0.1.0" then
    print("Consider reformatting to version 0.1.1")
    os.execute(projfile.tasks[task])
    return
end

if not projfile.tasks[task] then
    print("Task `" .. task .. "` not found in projfile.")
    return
end

local uv = require("luv")
local is_tty = uv.guess_handle(1) == "tty"

local SYMBOL = "[*] "
local MESSAGE = "Executing task `" .. task .. "`"
local PREFIX = "$ "
if is_tty then
    SYMBOL = COLORS.SYMBOL_COLOR .. " * " .. COLORS.RESET .. " "
    MESSAGE = COLORS.BOLD .. "Executing task" .. " `" .. task .. "`"
    PREFIX = COLORS.PURPLE .. "$ " .. COLORS.RESET
end

print(SYMBOL .. MESSAGE)
for _, command in ipairs(projfile.tasks[task]) do
    if type(command) == "table" then
        if command["tag"] ~= nil then
            print(command.tag)
        end
        for k, subcmd in pairs(command) do
            if (k ~= "tag") then
                print(PREFIX .. subcmd)
                os.execute(subcmd)
            end
        end
    else
        print(PREFIX .. command)
        os.execute(command)
    end
end
