#!/usr/bin/env bash

set -e

if ! tmux info &>/dev/null || ! tmux list-sessions &>/dev/null; then
    echo "No tmux sessions to kill."
    exit 0
fi

current=""
if [ -n "$TMUX" ]; then
    current=$(tmux display-message -p '#S')
fi

# shellcheck disable=SC2016
session=$( \
tmux list-sessions -F "|RESET|#S: #{?session_grouped, (group #{session_group}: #{session_group_list}),}#{?#{==:#{session_name},$current},|WHITE|(|GREEN||BOLD|current|WHITE|),#{?session_attached,|WHITE|(|BRIGHTBLUE||BOLD|attached|WHITE|),|WHITE|(|RED||BOLD|unattached|WHITE|)}}" \
| awk -v cur="$current" '{
        gsub(/\|GREEN\|/,       "\033[1;32m")
        gsub(/\|RESET\|/,       "\033[1;0m")
        gsub(/\|CYAN\|/,        "\033[1;36m")
        gsub(/\|BLACK\|/,       "\033[30m")
        gsub(/\|ITALICS\|/,     "\033[3m")
        gsub(/\|YELLOW\|/,      "\033[1;33m")
        gsub(/\|BOLD\|/,        "\033[1m")
        gsub(/\|WHITE\|/,       "\033[1;37m")
        gsub(/\|MAGENTA\|/,     "\033[1;35m")
        gsub(/\|BRIGHTBLUE\|/,  "\033[1;34m")
        gsub(/\|RED\|/,         "\033[1;31m")

        print
    }' \
| fzf --ansi \
    --reverse \
    --height=100% \
    --preview-window=right:85% \
    --preview 'bash -c '\''
        line="$1"
        session=$(printf "%s" "$line" | sed "s/\x1b\[[0-9;]*m//g" | cut -d: -f1)
        active_win=$(tmux list-windows -t "$session" -F "#{?#{window_active},#{window_index},}" | grep -v "^\$")
        active_pane=$(tmux list-panes -t "$session:$active_win" -F "#{?#{pane_active},#{pane_index},}" | grep -v "^\$")
        tmux capture-pane -pet "$session:$active_win.$active_pane"
        '\''  -- {} ' \
| awk -F: '{print $1}')

[ -z "$session" ] && exit 0

confirm=$(printf "No\nYes\n" | \
  fzf \
    --preview='' \
    --height=40% \
    --reverse \
    --no-info \
    --prompt="Kill session '$session'? " \
    --bind 'esc:abort' \
    --select-1)

[ "$confirm" = "Yes" ] || exit 0

tmux kill-session -t "$session"
