#!/usr/bin/env bash

fullpath=$(pick-project) || exit 0
proj=$(basename "$fullpath")
session="${proj//./_}"
if tmux has-session -t "$session" 2>/dev/null; then
    if [ -n "$TMUX" ]; then
        tmux switch-client -t "$session"
    else
        tmux attach -t "$session"
    fi
else
    if [ -n "$TMUX" ]; then
        TMUX='' tmux new-session -d -s "$session" -c "$fullpath"
        tmux switch-client -t "$session"
    else
        tmux new-session -s "$session" -c "$fullpath"
    fi
fi
